// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXMbK0vjPhsSWZBRu1gtSJeTjkV__r33o',
    appId: '1:878413363701:android:bd7e72b6cc3d43a5f048bc',
    messagingSenderId: '878413363701',
    projectId: 'billing-app-4ddfa',
    storageBucket: 'billing-app-4ddfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYsCH6ATjsDrXSNMQd9Oq0mYU1DHpn5gY',
    appId: '1:878413363701:ios:206ddbe8a43be82bf048bc',
    messagingSenderId: '878413363701',
    projectId: 'billing-app-4ddfa',
    storageBucket: 'billing-app-4ddfa.firebasestorage.app',
    iosBundleId: 'com.example.billingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8P-xvw57JoGM8B9Swb1Bl6e_hNQd6pks',
    appId: '1:878413363701:web:7bd104114d1fe6ccf048bc',
    messagingSenderId: '878413363701',
    projectId: 'billing-app-4ddfa',
    authDomain: 'billing-app-4ddfa.firebaseapp.com',
    storageBucket: 'billing-app-4ddfa.firebasestorage.app',
    measurementId: 'G-EYK8EKFRLC',
  );
}
